### ISSUE TITLE
Can't view or copy address

### ISSUE THREAD

**Issue by dada1134** [cronoh/raivault#2]
In the history tab, there is no way to view or even copy the entire address or hash no matter how wide the window is.
It would be nice if it was possible to copy any address or hash anywhere in the UI by right-clicking and then click copy in the context menu.

![image](https://user-images.githubusercontent.com/13734138/34703449-4b206666-f4f3-11e7-9e94-69fe437f1315.png)

**Comment by cronoh** [comment]
I'm working on adding a new display component for the account names, which will allow you to view the full address, copy it, or add it to the address book from anywhere in the app.  I believe that should fix this issue - expect it in the next release.

Thanks for the feedback!

**Comment by cronoh** [comment]
You should now be able to use the Account Viewer to copy any address - all of the links in Account History and other views have been converted to open the account viewer.  Closing for now but let me know if this doesn't solve your problem.  Thanks for reporting this!
